# ___Python libraries___
------------

In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt

## ___NumPy___

In [4]:
np.array([np.sqrt(i) for i in range(50, 100)], dtype = np.float64)

array([7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232527,
       8.66025404, 8.71779789, 8.77496439, 8.83176087, 8.88819442,
       8.94427191, 9.        , 9.05538514, 9.11043358, 9.16515139,
       9.21954446, 9.2736185 , 9.32737905, 9.38083152, 9.43398113,
       9.48683298, 9.53939201, 9.59166305, 9.64365076, 9.69535971,
       9.74679434, 9.79795897, 9.8488578 , 9.89949494, 9.94987437])

In [6]:
squares = np.array([[i for i in range(100)], [i * i for i in range(100)]])

In [9]:
squares[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
squares[1, :]

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [15]:
all(squares[1, :] == squares[1])

True

In [16]:
tuples = np.array([(i, i * i) for i in range(100)])

In [19]:
tuples[0]

array([0, 0])

In [23]:
tuples[:10]

array([[ 0,  0],
       [ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64],
       [ 9, 81]])

In [21]:
tuples[:, 0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
tuples[:, 1]

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [27]:
np.full(shape = (2, 12), fill_value = 4)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

## ___SciPy___

In [28]:
scipy.stats.norm.rvs(loc = 10, scale = 5, size = 100)

array([15.21066356,  6.36924338,  5.20330723, 11.26031226, 11.51351643,
        8.85906033, 11.98094657,  3.07646889, 14.78339689,  6.57384171,
       11.84876828, 10.26995109,  8.47567525,  9.78329856,  3.27050048,
       10.28016044,  2.86287285, -0.15464979, 19.93140277,  9.04603032,
       16.5595278 , 13.42653103,  4.46053682,  2.9156544 ,  8.73679977,
        7.84527351,  6.63166208, 10.56590682,  9.04850905, 16.34172243,
       13.18284984, 20.91493612, 12.84432524,  0.7993179 , 16.15126898,
        0.85078775, 10.06125054,  1.55286949,  8.9847512 , 10.50746403,
        8.9699462 ,  7.2590729 , 13.76193818,  3.33519104,  9.4553673 ,
       11.91057376,  8.71839557,  5.97451882, 13.68663154, 11.87644404,
       14.45555544, 16.65388786, 14.84304124,  5.76540624, 10.15198806,
        2.25694222,  6.72033969, 12.60265937, 10.97495944, 17.56662859,
       13.1262827 , 12.27886207,  5.83095492,  8.62139842,  5.06334423,
        7.9955695 , 14.95670973,  1.13487308,  3.30268657, 10.93

In [30]:
x = scipy.stats.t.rvs(size = 1000, df = 11)

In [31]:
scipy.stats.describe(x)

DescribeResult(nobs=1000, minmax=(-3.8938950268073547, 4.132028299433391), mean=-0.004939607666726025, variance=1.2710430608461682, skewness=-0.045328034401980424, kurtosis=0.6456830410955265)